package com.xsg.common.printer.template;


import com.xsg.common.printer.constants.FontSizeEnum;
import com.xsg.common.printer.core.PrintTemplate;
import com.xsg.common.printer.core.TemplateFluent;
import com.xsg.common.printer.model.XsgFiled;
import com.xsg.common.printer.model.XsgTemplate;
import com.xsg.common.printer.vo.TemplateVo;

/**
 * @author 高总辉
 * @desc 打印模板
 * @date 2020/12/9 3:28 下午
 */
public class TemplateConstants {

//    private static String basePath = "/usr/share/fonts/";
    private static String basePath = "D:\\work\\image\\";

    /**
     * 包裹联
     * @return
     */
    public static XsgTemplate getPkgTemplate () {
        TemplateFluent fluent = TemplateFluent.template();
        int height = 100*8;
        int width = 70*8;
        fluent.start(height, width, 1, true)
                .row(10*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("pickupCode").setValue("#38").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(8).setTop(2*8 + 3).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(23*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "sz_logo.png"), PrintTemplate.getDefaultMargin().setLeft(4*8).setTop(15), 6*8, 19*8)
                        )
                        .cellH(37*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setValue("小高快送"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(15).setRight(0), FontSizeEnum.MIDDLE)
                                .textElement(new XsgFiled<TemplateVo>().setName("serviceTel").setTitle("客服:").setValue("15613874848"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(45), FontSizeEnum.MIDDLE)
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("endStationName").setValue("罗湖").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(2*8).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("streetName").setValue("坂田街道"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(3*8), FontSizeEnum.MIDDLE)
                        )
                )
                .rowX(18*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "收.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(5*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptCustomer").setValue("雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptPhone").setValue("18129858526"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(6).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(9*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("receiptAddress").setValue("江西省九江市都昌县都昌一中 老校区一栋106 雪人汽车维修厂"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(1).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(15*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "寄.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("shipperCustomer").setValue("大石头汽配中心"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(3*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperPhone").setValue("18129872727"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(2).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(8*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperAddress").setValue("江西省上饶市鄱阳县银宝湖二中老校区一栋106大石头汽配"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(27*8, TemplateFluent.Cell.create()
                        .cell(39*8, TemplateFluent.Element.create()
                                .qrCodeElement(new XsgFiled<TemplateVo>().setName("packageNo").setValue("BC20122238900-01"),  PrintTemplate.getDefaultMargin().setLeft(9*8).setTop(2*7),20*8, 20*8)
                                .textElement(new XsgFiled<TemplateVo>().setName("packageNo").setTitle("包裹号:").setValue("BC2012223890080-01").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(20*8 + 3*8).setRight(0).setBottom(0), FontSizeEnum.SMALL)
                        )
                        .cellH(32*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("currentPackageNum").setValue("3/5"),  PrintTemplate.getDefaultMargin().setLeft(7*8).setTop(8*8).setRight(0), FontSizeEnum.BIG)
                                .texBElement(new XsgFiled<TemplateVo>().setName("packageDetail").setValue("100超大100大100中100小"),  PrintTemplate.getDefaultMargin().setLeft(7*8).setTop(8*8 + 50).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("remark").setTitle("备注: ").setValue("这里有很多东西需要帮忙一起搬回家，然后放在那个"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(19).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .row(6*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("startStationName").setTitle("始发: ").setValue("龙华悟红尘站点").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("payType").setTitle("结算: ").setValue("余额支付"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .rowH(2*8, TemplateFluent.Cell.create()
                        .cellH(45*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printTime").setTitle("打印时间:").setValue("2020-12-10 12:56:30"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(7).setRight(0).setRight(0), FontSizeEnum.SMALL)
                        )
                        .cellH(25*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printBy").setTitle("打印人:").setValue("高总辉"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(7).setRight(0), FontSizeEnum.SMALL)
                        )
                )
        ;
        return fluent.end();
    }


    /**
     * 签收联
     * @return
     */
    public static XsgTemplate getQsTemplate () {
        TemplateFluent fluent = TemplateFluent.template();
        int height = 100*8;
        int width = 70*8;
        fluent.start(height, width, 1, true)
                .row(10*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("pickupCode").setValue("#38").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(8).setTop(2*8 + 3).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(23*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "sz_logo.png"), PrintTemplate.getDefaultMargin().setLeft(4*8).setTop(15), 6*8, 19*8)
                        )
                        .cellH(37*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setValue("小高快送"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(15).setRight(0), FontSizeEnum.MIDDLE)
                                .textElement(new XsgFiled<TemplateVo>().setName("serviceTel").setTitle("客服:").setValue("15613874848"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(45), FontSizeEnum.MIDDLE)
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("endStationName").setValue("罗湖").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(2*8).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("streetName").setValue("坂田街道"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(3*8), FontSizeEnum.MIDDLE)
                        )
                )
                .rowX(18*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "收.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(5*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptCustomer").setValue("雪人汽修中心").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptPhone").setValue("18129858526"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(6).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(9*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("receiptAddress").setValue("江西省九江市都昌县都昌一中 老校区一栋106 雪人汽车维修厂"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(1).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(15*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "寄.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("shipperCustomer").setValue("大石头汽配中心"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(3*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperPhone").setValue("18129872727"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(2).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(8*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperAddress").setValue("江西省上饶市鄱阳县银宝湖二中老校区一栋106大石头汽配"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(27*8, TemplateFluent.Cell.create()
                        .cell(15*8, TemplateFluent.Row.create()
                                .row(14*8, TemplateFluent.Cell.create()
                                        .cellH(15*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("confirmCode").setValue("88"),  PrintTemplate.getDefaultMargin().setLeft(30).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                                                .texBElement(new XsgFiled<TemplateVo>().setName("startStationName").setValue("龙华龙华"),  PrintTemplate.getDefaultMargin().setLeft(15).setTop(8*8).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(13*8, TemplateFluent.Cell.create()
                                        .cellH(15*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("qty").setValue("5件"),  PrintTemplate.getDefaultMargin().setLeft(25).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                                                .textElement(new XsgFiled<TemplateVo>().setName("packageDetail").setValue("1超大333大111中222小"),  PrintTemplate.getDefaultMargin().setLeft(25).setTop(8*8).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                        .cell(35*8, TemplateFluent.Element.create()
                                .qrCodeElement(new XsgFiled<TemplateVo>().setName("waybillId").setValue("BC2012187480039"),  PrintTemplate.getDefaultMargin().setLeft(7*8 + 4).setTop(2*7),20*8, 20*8)
                                .textElement(new XsgFiled<TemplateVo>().setName("waybillId").setTitle("单号:").setValue("BC2012187480039"),  PrintTemplate.getDefaultMargin().setLeft(4*8).setTop(20*8 + 3*8).setRight(0).setBottom(0), FontSizeEnum.SMALL)
                        )
                        .cellH(20*8, TemplateFluent.Row.create()
                                .row(13*8, TemplateFluent.Cell.create()
                                        .cellH(20*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("hasColl").setValue("有代收"),  PrintTemplate.getDefaultMargin().setLeft(3*8 + 2).setTop(4*8).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .rowH(14*8, TemplateFluent.Cell.create()
                                        .cellH(20*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setValue("收件签字"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(1*8).setRight(0), FontSizeEnum.MIDDLE)
                                                .textElement(new XsgFiled<TemplateVo>().setValue("年  月  日"),  PrintTemplate.getDefaultMargin().setLeft(5*8).setTop(11*8).setRight(0), FontSizeEnum.SMALL)
                                        )
                                )
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("remark").setTitle("备注: ").setValue("这里有很多东西需要帮忙一起搬回家，然后放在那个"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(19).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .row(6*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("payType").setTitle("结算: ").setValue("余额支付"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .rowH(2*8, TemplateFluent.Cell.create()
                        .cellH(45*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printTime").setTitle("打印时间:").setValue("2020-12-10 12:56:30"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(7).setRight(0).setRight(0), FontSizeEnum.SMALL)
                        )
                        .cellH(25*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printBy").setTitle("打印人:").setValue("高总辉"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(7).setRight(0), FontSizeEnum.SMALL)
                        )
                )
        ;
        return fluent.end();
    }

    /**
     * 退货包裹联
     * @return
     */
    public static XsgTemplate getTuHuoPkgTemplate () {
        TemplateFluent fluent = TemplateFluent.template();
        int height = 100*8;
        int width = 70*8;
        fluent.start(height, width, 1, true)
                .row(10*8, TemplateFluent.Cell.create()
                        .cellH(31*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "xs_logo.png"), PrintTemplate.getDefaultMargin().setLeft(13*8 + 6).setTop(15), 6*8, 19*8)
                        )
                        .cellH(30*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setValue("小高快送"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(15).setRight(0), FontSizeEnum.MIDDLE)
                                .textElement(new XsgFiled<TemplateVo>().setName("serviceTel").setTitle("客服:").setValue("15613874848"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(45), FontSizeEnum.MIDDLE)
                        )
                        .cellH(9*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "T.png"), PrintTemplate.getDefaultMargin().setLeft(0).setTop(0), 10*8 - 1, 9*8)
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("endStationName").setValue("罗湖").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(2*8).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("streetName").setValue("坂田街道"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(3*8), FontSizeEnum.MIDDLE)
                        )
                )
                .rowX(18*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "收.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(5*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptCustomer").setValue("雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心雪人汽修中心").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptPhone").setValue("18129858526"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(6).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(9*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("receiptAddress").setValue("江西省九江市都昌县都昌一中 老校区一栋106 雪人汽车维修厂"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(1).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(15*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "寄.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("shipperCustomer").setValue("大石头汽配中心"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(3*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperPhone").setValue("18129872727"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(2).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(8*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperAddress").setValue("江西省上饶市鄱阳县银宝湖二中老校区一栋106大石头汽配"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(27*8, TemplateFluent.Cell.create()
                        .cell(39*8, TemplateFluent.Element.create()
                                .qrCodeElement(new XsgFiled<TemplateVo>().setName("packageNo").setValue("BC20122238900-01"),  PrintTemplate.getDefaultMargin().setLeft(9*8).setTop(2*7),20*8, 20*8)
                                .textElement(new XsgFiled<TemplateVo>().setName("packageNo").setTitle("包裹号:").setValue("BC20122238900-01").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(20*8 + 3*8).setRight(0).setBottom(0), FontSizeEnum.SMALL)
                        )
                        .cellH(32*8, TemplateFluent.Row.create()
                                .row(14*8, TemplateFluent.Cell.create()
                                        .cellH(32*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("currentPackageNum").setValue("3/5"),  PrintTemplate.getDefaultMargin().setLeft(7*8).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                                                .texBElement(new XsgFiled<TemplateVo>().setName("packageDetail").setValue("100超大100大100中100小"),  PrintTemplate.getDefaultMargin().setLeft(7*8).setTop(2*8 + 50).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .row(13*8, TemplateFluent.Cell.create()
                                        .cellH(32*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setValue("签收即您对货物品质和数量确认无误"),  PrintTemplate.getDefaultMargin().setLeft(3*8).setTop(3*8).setRight(0), FontSizeEnum.SMALL)
                                        )
                                )
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("remark").setTitle("备注: ").setValue("这里有很多东西需要帮忙一起搬回家，然后放在那个"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(19).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .row(6*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("startStationName").setTitle("始发: ").setValue("龙华悟红尘站点").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("payType").setTitle("结算: ").setValue("余额支付"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .rowH(2*8, TemplateFluent.Cell.create()
                        .cellH(45*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printTime").setTitle("打印时间:").setValue("2020-12-10 12:56:30"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(7).setRight(0).setRight(0), FontSizeEnum.SMALL)
                        )
                        .cellH(25*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printBy").setTitle("打印人:").setValue("高总辉"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(7).setRight(0), FontSizeEnum.SMALL)
                        )
                )
        ;
        return fluent.end();
    }

    /**
     * 退货签收联
     * @return
     */
    public static XsgTemplate getTuHuoQsTemplate() {
        TemplateFluent fluent = TemplateFluent.template();
        int height = 100*8;
        int width = 70*8;
        fluent.start(height, width, 1, true)
                .row(10*8, TemplateFluent.Cell.create()
                        .cellH(31*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "sz_logo.png"), PrintTemplate.getDefaultMargin().setLeft(13*8 + 6).setTop(15), 6*8, 19*8)
                        )
                        .cellH(30*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setValue("小高快送"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(15).setRight(0), FontSizeEnum.MIDDLE)
                                .textElement(new XsgFiled<TemplateVo>().setName("serviceTel").setTitle("客服:").setValue("15613874848"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(45), FontSizeEnum.MIDDLE)
                        )
                        .cellH(9*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "T.png"), PrintTemplate.getDefaultMargin().setLeft(0).setTop(0), 10*8 - 1, 9*8)
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(20*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("endStationName").setValue("罗湖").setNeedFeedLine(false).setFit(true),  PrintTemplate.getDefaultMargin().setLeft(2*8).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                        )
                        .cellH(50*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("streetName").setValue("坂田街道"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(3*8), FontSizeEnum.MIDDLE)
                        )
                )
                .rowX(18*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "收.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(5*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptCustomer").setValue("雪人汽修中心").setNeedFeedLine(false),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("receiptPhone").setValue("18129858526"),  PrintTemplate.getDefaultMargin().setLeft(0).setTop(6).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(9*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("receiptAddress").setValue("江西省九江市都昌县都昌一中 老校区一栋106 雪人汽车维修厂"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(1).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(15*8, TemplateFluent.Cell.create()
                        .cellH(10*8, TemplateFluent.Element.create()
                                .imageElement(new XsgFiled<TemplateVo>().setValue(basePath + "寄.png"), PrintTemplate.getDefaultMargin().setLeft(5).setTop(10), 8*8, 8*8)
                        )
                        .cellH(60*8, TemplateFluent.Row.create()
                                .rowH(4*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("shipperCustomer").setValue("大石头汽配中心"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(3*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperPhone").setValue("18129872727"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(2).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(8*8, TemplateFluent.Cell.create()
                                        .cellH(60*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setName("shipperAddress").setValue("江西省上饶市鄱阳县银宝湖二中老校区一栋106大石头汽配"),  PrintTemplate.getDefaultMargin().setLeft(1).setTop(5).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                )
                .row(27*8, TemplateFluent.Cell.create()
                        .cell(15*8, TemplateFluent.Row.create()
                                .row(14*8, TemplateFluent.Cell.create()
                                        .cellH(15*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("confirmCode").setValue("88"),  PrintTemplate.getDefaultMargin().setLeft(30).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                                                .texBElement(new XsgFiled<TemplateVo>().setName("startStationName").setValue("龙华龙华"),  PrintTemplate.getDefaultMargin().setLeft(15).setTop(8*8).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                                .rowH(13*8, TemplateFluent.Cell.create()
                                        .cellH(15*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("qty").setValue("5件"),  PrintTemplate.getDefaultMargin().setLeft(25).setTop(2*8).setRight(0), FontSizeEnum.BIG)
                                                .textElement(new XsgFiled<TemplateVo>().setName("packageDetail").setValue("1超大333大111中222小"),  PrintTemplate.getDefaultMargin().setLeft(25).setTop(8*8).setRight(0), FontSizeEnum.MIDDLE)
                                        )
                                )
                        )
                        .cell(35*8, TemplateFluent.Element.create()
                                .qrCodeElement(new XsgFiled<TemplateVo>().setName("waybillId").setValue("BC2012187480039"),  PrintTemplate.getDefaultMargin().setLeft(7*8 + 4).setTop(2*7),20*8, 20*8)
                                .textElement(new XsgFiled<TemplateVo>().setName("waybillId").setTitle("单号:").setValue("BC201218748003"),  PrintTemplate.getDefaultMargin().setLeft(4*8).setTop(20*8 + 3*8).setRight(0).setBottom(0), FontSizeEnum.SMALL)
                        )
                        .cellH(20*8, TemplateFluent.Row.create()
                                .row(6*8, TemplateFluent.Cell.create()
                                        .cellH(20*8, TemplateFluent.Element.create()
                                                .texBElement(new XsgFiled<TemplateVo>().setName("hasColl").setValue("有代收"),  PrintTemplate.getDefaultMargin().setLeft(4*8).setTop(3).setRight(0), FontSizeEnum.BIG)
                                        )
                                )
                                .row(11*8, TemplateFluent.Cell.create()
                                        .cellH(20*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setValue("签收即您对货物品质和数量确认无误"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(1*8).setRight(0), FontSizeEnum.SMALL)
                                        )
                                )
                                .rowH(10*8, TemplateFluent.Cell.create()
                                        .cellH(20*8, TemplateFluent.Element.create()
                                                .textElement(new XsgFiled<TemplateVo>().setValue("收件签字"),  PrintTemplate.getDefaultMargin().setLeft(1*8).setTop(1*8).setRight(0), FontSizeEnum.SMALL)
                                                .textElement(new XsgFiled<TemplateVo>().setValue("年  月  日"),  PrintTemplate.getDefaultMargin().setLeft(6*8).setTop(7*8 - 3).setRight(0), FontSizeEnum.SMALL)
                                        )
                                )
                        )
                )
                .row(8*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("remark").setTitle("备注: ").setValue("这里有很多东西需要帮忙一起搬回家，然后放在那个"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(19).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .row(6*8, TemplateFluent.Cell.create()
                        .cellH(70*8, TemplateFluent.Element.create()
                                .texBElement(new XsgFiled<TemplateVo>().setName("payType").setTitle("结算: ").setValue("余额支付"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(12).setRight(0), FontSizeEnum.MIDDLE)
                        )
                )
                .rowH(2*8, TemplateFluent.Cell.create()
                        .cellH(45*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printTime").setTitle("打印时间:").setValue("2020-12-10 12:56:30"),  PrintTemplate.getDefaultMargin().setLeft(10).setTop(7).setRight(0).setRight(0), FontSizeEnum.SMALL)
                        )
                        .cellH(25*8, TemplateFluent.Element.create()
                                .textElement(new XsgFiled<TemplateVo>().setName("printBy").setTitle("打印人:").setValue("高总辉"),  PrintTemplate.getDefaultMargin().setLeft(20).setTop(7).setRight(0), FontSizeEnum.SMALL)
                        )
                )
        ;
        return fluent.end();
    }
}
